### ISSUE TITLE
https://github.com/shreyas-jadhav/roundware-web-template not compiling

### ISSUE THREAD

**Issue by gavspav** [roundware/roundware-web-template#13]
I am getting errors when trying to build this project. I can test it locally (with the errors) but I get multiple errors similar to this one:

Property 'autoResetTimeSeconds' does not exist on type '{ ROUNDWARE_SERVER_URL: string; ROUNDWARE_SERVER_BASE_URL: string; ROUNDWARE_DEFAULT_PROJECT_ID: number; ROUNDWARE_INITIAL_LATITUDE: number; ROUNDWARE_INITIAL_LONGITUDE: number; ... 22 more ...; zoom: { ...; }; }'.

**Comment by hburgund** [comment]
this error is due to a missing entry in the `config.json` file as best I can tell. Try adding:

```"autoResetTimeSeconds": 0,```

to your `config.json` and see if that fixes this error. If so, the additional similar errors will likely be fixed by adding other corresponding entries. It is strange if you are missing this entry as it has been committed to the repo, so maybe there were some merging issues for you?

**Comment by gavspav** [comment]
Ok yes, I didn't realise the config file had changed and just copied my old config across. Sorted now, thanks
